### ISSUE TITLE
Unit conversion app

### ISSUE THREAD

**Issue by cmutel** [Depart-de-Sentier/sentier.dev#29]
**This issue has been moved to https://github.com/Depart-de-Sentier/brightcon-2024-material/issues/1 for the Brightcon hackathon**

# Overview

We have a [database with units](https://github.com/sentier-dev/sentier_vocab), code for a [specific type of unit conversion](https://github.com/brightway-lca/brightway2-io/blob/main/bw2io/strategies/sentier/simapro_units.py), and the need for a general API for converting units in the future.

## User stories

Let's build a webapp that can do the following:

- Given a unit string, tell me what the preferred term and URI for that unit concept are in other systems
- Given a unit concept URI, give me all known units in the same quantity type for a given unit system including conversion factors
- Given a unit string which doesn't match a preferred term exactly, give me search results for that term which includes descriptions and alternative terms from all systems

And finally, tie all this together so you can start typing a unit, pick the right one from a dropdown, and then get tables of conversion factors for each system we include.

## Unit systems

The unit systems we already have:
- SimaPro
- ecoinvent (only URIs, need to include other data for search unless we want to query their API as well)
- QUDT

Unit systems I would like to have:
- FedEFL / lcacommons.gov
- OpenLCA

## Tasks

- [ ] Pick architecture for frontend and backend
- [ ] Build an API backend which can support the user stories and draws data from our Fuseki database
- [ ] Deploy the API
- [ ] Design the frontend
- [ ] Implement the frontend
- [ ] Add missing unit systems
- [ ] Fix search on skosmos and expose API
- [ ] Implement varnish cache on skosmos deployment
- [ ] Have correct skosmos deployed on our cloud architecture

Stretch goals:

- Build a client library on top of the API

## Skosmos search

This is possibly hard. We have a search index via skosmos (which should also have an API), but it only searches on `prefLabel` (see search result for [btu](https://vocab.sentier.dev/qudt/en/search?clang=en&q=btu&vocabs=) versus [british](https://vocab.sentier.dev/qudt/en/search?clang=en&q=british&vocabs=)), and maybe on [altLabel](https://www.w3.org/TR/skos-reference/#labels). We are currently using [notation](https://www.w3.org/TR/skos-primer/#secnotations) ("Notations are symbols which are not normally recognizable as words or sequences of words in any natural language and are thus usable independently of natural-language contexts"), but we could change these to `altLabel`, or add `altLabel` in addition to `notation` (there are strings, even if they have custom data types, so should be fine for being instances of RDF plain literal).

**Comment by cmutel** [comment]
Moved to https://github.com/Depart-de-Sentier/brightcon-2024-material/issues/1
